# yaml-language-server: $schema=./schema.default.json
# Minimal Germany single-day configuration

run:
  name: "germany"
  disable_progressbar: true
  shared_resources:
    policy: false

scenario:
  clusters:
  - all # no clustering
  opts:
  - "" # base electricity model
  planning_horizons:
  - 2025

load:
  supplement_synthetic: false

electricity:
  powerplants_filter: "Capacity.notna() and Capacity > 0"
  custom_powerplants: false
  conventional_carriers:
    - OCGT
    - CCGT
    - coal
    - lignite
    - nuclear
    - oil
    - biomass
    - biogas
    - hydro
    - ror
    - PHS
    - solar
    - onwind
    - offwind-ac
    - offwind-dc
  extendable_carriers:
    Generator: []
  estimate_renewable_capacities:
    enable: false

countries: ['DE']

snapshots:
  start: "2025-05-14"
  end: "2025-05-16"

atlite:
  default_cutout: "europe-2025-sarah3-era5"

renewable:
  onwind:
    corine: false
  solar:
    corine: false
  solar-hsat:
    corine: false

solving:
  solver:
    name: highs
    options: highs-default

  check_objective:
    enable: false

data:
  cutout:
    source: archive
    version: v1.0
