# yaml-language-server: $schema=./schema.default.json
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "germany-adm"
  disable_progressbar: true
  shared_resources:
    policy: false

scenario:
  clusters:
  - adm
  opts:
  - ''
  planning_horizons:
  - 2025

countries: ['DE']

snapshots:
  start: "2025-01-01"
  end: "2025-12-31"

load:
  supplement_synthetic: false

electricity:
  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]
  estimate_renewable_capacities:
    enable: true
    from_powerplantmatching: true
    year: 2025
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV: solar

atlite:
  default_cutout: "europe-2025-sarah3-era5"

renewable:
  onwind:
    corine: false
  solar:
    corine: false
  solar-hsat:
    corine: false

clustering:
  mode: administrative
  administrative:
    level: 2
  exclude_carriers: []
  temporal:
    resolution_elec: 24h

solving:
  solver:
    name: highs
    options: highs-default
  check_objective:
    enable: false

data:
  cutout:
    source: archive
    version: v1.0
