# yaml-language-server: $schema=./schema.default.json
# Minimal Germany single-day configuration

run:
  name: "germany"
  disable_progressbar: true
  shared_resources:
    policy: false

scenario:
  clusters:
  - all # no clustering
  opts:
  - "" # base electricity model
  planning_horizons:
  - 2025

load:
  supplement_synthetic: false

electricity:
  powerplants_filter: "p_nom.notna() and p_nom > 0"
  custom_powerplants: false
  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]
  estimate_renewable_capacities:
    enable: true
    from_powerplantmatching: true
    year: 2025
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV: solar

countries: ['DE']

snapshots:
  start: "2025-05-14"
  end: "2025-05-16"

atlite:
  default_cutout: "europe-2025-sarah3-era5"

renewable:
  onwind:
    corine: false
  solar:
    corine: false
  solar-hsat:
    corine: false

solving:
  solver:
    name: highs
    options: highs-default

  check_objective:
    enable: false

data:
  cutout:
    source: archive
    version: v1.0
