# yaml-language-server: $schema=./schema.default.json
# Minimal Germany single-day configuration

run:
  name: "germany_basecase"
  disable_progressbarcd : true
  shared_resources:
    policy: false

scenario:
  clusters:
  - "450" #max clusters
  opts:
  - "windy"
  - "not-windy"
  - "wind-variability"
  - "present"
  planning_horizons:
  - 2025

countries: ['DE']

electricity:
  custom_powerplants: false
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc]
  estimate_renewable_capacities:
    enable: true
    from_powerplantmatching: true
    from_irenastat: true # added 22.04.
    year: 2025
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac # assuming that all offshore wind is AC
      PV: solar
  extendable_carriers: 
    Generator: [] # no extandable generators to match the status quo
    
atlite:
  default_cutout: "europe-2025-sarah3-era5"

# do not remove: does not work
renewable:
  onwind:
    corine: false
  solar:
    corine: false
  solar-hsat:
    corine: false

load:
# Whether to supplement missing data for selected time period 
# should be supplemented by synthetic data from Zenodo.
  supplement_synthetic: false 

solving:
  solver:
    name: highs
    options: highs-default
